server:
  port: 9000

spring:
  application:
    name: professional-diversion-student
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    url: jdbc:mysql://localhost:3306/professional_diversion?zeroDateTimeBehavior=convertToNull&?useSSL=false&allowMultiQueries=true&setUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: qaz147896325
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 2319770566@qq.com
    password: attubofaxbydebjh
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置

logging:
  level:
    root: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: false
  openapi:
    title: 专业分流系统教师端接口文档
    description: "专业分流系统教师端接口文档"
    email: 3173514223@qq.com
    concat: 林光远
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.glxy.pro.controller

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  # 7天免登录
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

uni-sms:
  access-key-id: NfrEky46dySF3DHVaqbNChiKYDZ4ytMvwPc8YjezCV2h2yUZU # ak
  signature: 林光远测试 # 短信签名
  template-id: pub_verif_ttl3 # 短信模板ID

find-password:
  by-mail:
    subject: 广东工业大学管理学院

freemarker:
  cache:false
settings:
  classic_compatible:true
suffix: .html
charset: UTF-8
template-loader-path: classpath:/templates/